export const properties = [
  {
    image: "https://denver.wpresidence.net/wp-content/uploads/2014/05/3-2-525x328.jpeg",
    title: "Villa with Amazing View",
    type: "Studio",
    status: "For Sale",
    price: "$5,500,000",
    bedrooms: 5,
    bathrooms: 3,
    size: "250 ft²",
    featured: true,
  },
  {
    image: "https://denver.wpresidence.net/wp-content/uploads/2014/05/6-2-525x328.jpeg",
    title: "Townhouse for Sale",
    type: "Single Family Home",
    status: "For Sale",
    price: "$210,000",
    bedrooms: 3,
    bathrooms: 2,
    size: "150 ft²",
    featured: true,
  },
  {
    image: "https://denver.wpresidence.net/wp-content/uploads/2014/05/house2-e1683804196607-2-525x328.jpg",
    title: "Townhouse for Rent",
    type: "Multi Family House",
    status: "For Rent",
    price: "$100 / sq. ft.",
    bedrooms: 2,
    bathrooms: 5,
    size: "29000 ft²",
    featured: true,
  },
  {
    image: "https://denver.wpresidence.net/wp-content/uploads/2014/05/8-2-525x328.jpeg",
    title: "Gorgeous Studio for Rent",
    type: "Apartment",
    status: "For Sale",
    price: "$770,000",
    bedrooms: 5,
    bathrooms: 6,
    size: "190 ft²",
    featured: true,
  },
  {
    image: "https://denver.wpresidence.net/wp-content/uploads/2023/08/industrial-525x328.webp",
    title: "Office for Rent in Denver",
    type: "Commercial · Office · Shop",
    status: "For Rent",
    price: "$1,200 / month",
    bedrooms: 5,
    bathrooms: 3,
    size: "250 ft²",
  },
  {
    image: "https://denver.wpresidence.net/wp-content/uploads/2023/08/hospitaluty-1000x623-1-525x328.webp",
    title: "Office for Sale in Denver",
    type: "Commercial · Office · Shop",
    status: "For Sale",
    price: "$1,200,000",
    bedrooms: 5,
    bathrooms: 3,
    size: "250 ft²",
  },
  {
    image: "https://denver.wpresidence.net/wp-content/uploads/2023/08/kitchen_modern2-800-525x328.webp",
    title: "Studio in Denver",
    type: "Studio",
    status: "For Sale",
    price: "$120,000",
    bedrooms: 5,
    bathrooms: 3,
    size: "250 ft²",
  },
  {
    image: "https://denver.wpresidence.net/wp-content/uploads/2023/08/interior-1-525x328.webp",
    title: "Studio in Central City",
    type: "Studio",
    status: "For Sale",
    price: "$120,000",
    bedrooms: 5,
    bathrooms: 3,
    size: "250 ft²",
  },
  {
    image: "https://denver.wpresidence.net/wp-content/uploads/2023/08/white_living-1-525x328.webp",
    title: "Studio with Amazing View",
    type: "Studio",
    status: "For Sale",
    price: "$450,000",
    bedrooms: 5,
    bathrooms: 3,
    size: "250 ft²",
  },
  {
    image: "https://denver.wpresidence.net/wp-content/uploads/2014/05/interior-1500-4-525x328.jpeg",
    title: "Family Home for Sale",
    type: "Multi Family House",
    status: "For Rent",
    price: "$800 / month",
    bedrooms: 2,
    bathrooms: 4,
    size: "500 ft²",
  },
  {
    image: "https://denver.wpresidence.net/wp-content/uploads/2014/05/4-2-525x328.jpeg",
    title: "Apartment with Ocean View",
    type: "Condo",
    status: "For Sale",
    price: "$1,500,000",
    bedrooms: 2,
    bathrooms: 2,
    size: "700 ft²",
  },
  {
    image: "https://denver.wpresidence.net/wp-content/uploads/2014/05/house-copy-2-525x328.jpg",
    title: "Modern Condo for Rent",
    type: "Multi Family House",
    status: "For Rent",
    price: "$1,600 / month",
    bedrooms: 3,
    bathrooms: 2,
    size: "150 ft²",
  },
];